<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\UserPref;
use App\Services\Ai\Planner\PlannerProfileSyncService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AiPlannerAdversarialSeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            [
                'email' => 'rana.moukalled+attack1@hayetak.local',
                'first_name' => 'Rana',
                'last_name' => 'Moukalled',
                'username' => 'rana_moukalled_attack1',
                'gender' => 'female',
                'age' => 34,
                'height_cm' => 166,
                'weight_kg' => 61.4,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Maintain',
                'diet_name' => 'Gluten-Free',
                'allergies' => ['Wheat'],
                'has_medical_history' => true,
                'medical_history' => 'Celiac disease with occasional reflux flare-ups.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Travel/routine changes', 'Too restrictive'],
                'diet_failure_other' => 'Restaurant meals often caused accidental gluten exposure.',
                'prefs_settings' => [
                    'injury_history' => ['Wrist pain'],
                    'available_equipment' => ['bodyweight', 'resistance band'],
                    'preferred_workout_days' => ['monday', 'wednesday', 'friday'],
                ],
            ],
            [
                'email' => 'mira.haddad+attack2@hayetak.local',
                'first_name' => 'Mira',
                'last_name' => 'Haddad',
                'username' => 'mira_haddad_attack2',
                'gender' => 'female',
                'age' => 38,
                'height_cm' => 163,
                'weight_kg' => 67.9,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Low FODMAP',
                'allergies' => ['Garlic', 'Onion'],
                'has_medical_history' => true,
                'medical_history' => 'IBS with bloating triggered by garlic and onion.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Time/meal prep burden', 'Cravings'],
                'diet_failure_other' => 'Sauces and marinades frequently broke the low-FODMAP plan.',
                'prefs_settings' => [
                    'injury_history' => ['Lower back tightness'],
                    'available_equipment' => ['bodyweight', 'dumbbell'],
                    'preferred_workout_days' => ['monday', 'tuesday', 'thursday', 'saturday'],
                ],
            ],
            [
                'email' => 'yara.nasr+attack3@hayetak.local',
                'first_name' => 'Yara',
                'last_name' => 'Nasr',
                'username' => 'yara_nasr_attack3',
                'gender' => 'female',
                'age' => 27,
                'height_cm' => 169,
                'weight_kg' => 58.7,
                'dietary_goal' => 'Calorie Surplus',
                'fitness_goal' => 'Build Muscle',
                'diet_name' => 'Vegan',
                'allergies' => ['Soy', 'Tree Nuts'],
                'has_medical_history' => true,
                'medical_history' => 'Iron-deficiency anemia.',
                'activity_level' => 'Very Active',
                'workout_days_per_week' => 5,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Too expensive', 'Confusing guidance'],
                'diet_failure_other' => 'Most protein suggestions relied on soy or nuts.',
                'prefs_settings' => [
                    'injury_history' => ['Shoulder irritation'],
                    'available_equipment' => ['bodyweight', 'dumbbell', 'bench'],
                    'preferred_workout_days' => ['monday', 'tuesday', 'thursday', 'friday', 'saturday'],
                ],
            ],
            [
                'email' => 'karim.maalouf+attack4@hayetak.local',
                'first_name' => 'Karim',
                'last_name' => 'Maalouf',
                'username' => 'karim_maalouf_attack4',
                'gender' => 'male',
                'age' => 46,
                'height_cm' => 178,
                'weight_kg' => 91.2,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Maintain Strength',
                'diet_name' => 'DASH',
                'allergies' => ['Fish'],
                'has_medical_history' => true,
                'medical_history' => 'Hypertension with caffeine sensitivity and sleep apnea.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Lack of results', 'Social/lifestyle conflicts'],
                'diet_failure_other' => 'Pre-workout drinks and salty snacks kept creeping in.',
                'prefs_settings' => [
                    'injury_history' => ['Elbow tendinopathy'],
                    'available_equipment' => ['dumbbell', 'cable machine', 'leg press', 'bench'],
                    'preferred_workout_days' => ['monday', 'wednesday', 'friday'],
                ],
            ],
            [
                'email' => 'lynn.saad+attack5@hayetak.local',
                'first_name' => 'Lynn',
                'last_name' => 'Saad',
                'username' => 'lynn_saad_attack5',
                'gender' => 'female',
                'age' => 31,
                'height_cm' => 160,
                'weight_kg' => 64.8,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Recomposition',
                'diet_name' => 'Keto',
                'allergies' => ['Eggs', 'Milk'],
                'has_medical_history' => true,
                'medical_history' => 'Acid reflux and GERD symptoms after spicy or caffeinated foods.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Hunger/low energy', 'Too restrictive'],
                'diet_failure_other' => 'Many keto breakfast ideas conflicted with reflux and dairy.',
                'prefs_settings' => [
                    'injury_history' => ['Knee pain'],
                    'available_equipment' => ['bodyweight', 'dumbbell', 'kettlebell'],
                    'preferred_workout_days' => ['monday', 'tuesday', 'thursday', 'sunday'],
                ],
            ],
            [
                'email' => 'samir.tannous+attack6@hayetak.local',
                'first_name' => 'Samir',
                'last_name' => 'Tannous',
                'username' => 'samir_tannous_attack6',
                'gender' => 'male',
                'age' => 42,
                'height_cm' => 181,
                'weight_kg' => 88.5,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Maintain',
                'diet_name' => 'Mediterranean',
                'allergies' => ['Peanut', 'Shrimp'],
                'has_medical_history' => true,
                'medical_history' => 'Prediabetes and previous shoulder impingement.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Confusing guidance', 'Cravings'],
                'diet_failure_other' => 'Online snack suggestions kept recommending peanut butter.',
                'prefs_settings' => [
                    'injury_history' => ['Shoulder impingement'],
                    'available_equipment' => ['bodyweight', 'resistance band', 'dumbbell'],
                    'preferred_workout_days' => ['monday', 'wednesday', 'friday', 'sunday'],
                ],
            ],
            [
                'email' => 'hiba.khoury+attack7@hayetak.local',
                'first_name' => 'Hiba',
                'last_name' => 'Khoury',
                'username' => 'hiba_khoury_attack7',
                'gender' => 'female',
                'age' => 57,
                'height_cm' => 158,
                'weight_kg' => 74.3,
                'dietary_goal' => 'Maintenance',
                'fitness_goal' => 'Maintain Strength',
                'diet_name' => 'Vegetarian',
                'allergies' => ['Lupin', 'Celery'],
                'has_medical_history' => true,
                'medical_history' => 'Bilateral knee osteoarthritis and mild hypertension.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Lack of results', 'Too restrictive'],
                'diet_failure_other' => 'Jump-heavy home circuits made the knees flare quickly.',
                'prefs_settings' => [
                    'injury_history' => ['Knee osteoarthritis'],
                    'available_equipment' => ['bodyweight', 'chair'],
                    'preferred_workout_days' => ['tuesday', 'thursday', 'saturday'],
                ],
            ],
            [
                'email' => 'jad.fares+attack8@hayetak.local',
                'first_name' => 'Jad',
                'last_name' => 'Fares',
                'username' => 'jad_fares_attack8',
                'gender' => 'male',
                'age' => 40,
                'height_cm' => 176,
                'weight_kg' => 96.1,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Paleo',
                'allergies' => ['Tomato', 'Wheat'],
                'has_medical_history' => true,
                'medical_history' => 'Type 2 diabetes with fatty liver.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Medical reasons', 'Time/meal prep burden'],
                'diet_failure_other' => 'Fast meal ideas often turned into sugary drinks or bread-heavy snacks.',
                'prefs_settings' => [
                    'injury_history' => ['Ankle pain'],
                    'available_equipment' => ['bodyweight', 'dumbbell', 'stationary bike'],
                    'preferred_workout_days' => ['monday', 'wednesday', 'friday', 'saturday'],
                ],
            ],
            [
                'email' => 'tala.rahme+attack9@hayetak.local',
                'first_name' => 'Tala',
                'last_name' => 'Rahme',
                'username' => 'tala_rahme_attack9',
                'gender' => 'female',
                'age' => 35,
                'height_cm' => 167,
                'weight_kg' => 70.6,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Recomposition',
                'diet_name' => 'Intermittent Fasting',
                'allergies' => ['Sesame', 'Shellfish'],
                'has_medical_history' => true,
                'medical_history' => 'Fatty liver and migraine history.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Travel/routine changes', 'Cravings'],
                'diet_failure_other' => 'Late dinners and restaurant sauces often broke the plan.',
                'prefs_settings' => [
                    'injury_history' => ['Lower back pain'],
                    'available_equipment' => ['dumbbell', 'cable machine', 'lat pulldown', 'smith machine'],
                    'preferred_workout_days' => ['monday', 'tuesday', 'thursday', 'friday'],
                ],
            ],
            [
                'email' => 'noor.chehab+attack10@hayetak.local',
                'first_name' => 'Noor',
                'last_name' => 'Chehab',
                'username' => 'noor_chehab_attack10',
                'gender' => 'female',
                'age' => 29,
                'height_cm' => 171,
                'weight_kg' => 62.3,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Gluten-Free Low FODMAP',
                'allergies' => ['Peanut', 'Garlic'],
                'has_medical_history' => true,
                'medical_history' => 'IBS with celiac disease and occasional wrist pain.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Too restrictive', 'Too expensive'],
                'diet_failure_other' => 'Safe convenience foods were hard to find and repetitive.',
                'prefs_settings' => [
                    'injury_history' => ['Wrist pain', 'Shoulder irritation'],
                    'available_equipment' => ['bodyweight'],
                    'preferred_workout_days' => ['monday', 'wednesday', 'friday', 'sunday'],
                ],
            ],
        ];

        foreach ($profiles as $index => $profile) {
            $createdAt = now()->subDays(90 + ($index * 2));
            $prefsSettings = $profile['prefs_settings'] ?? [];
            unset($profile['prefs_settings']);

            $user = User::query()->updateOrCreate(
                ['email' => $profile['email']],
                [
                    'name' => $profile['first_name'].' '.$profile['last_name'],
                    'password' => Hash::make('password'),
                    'role' => User::ROLE_CLIENT,
                    'verified' => true,
                    'status' => 'active',
                    'created_at' => $createdAt,
                    'updated_at' => now(),
                    'email_verified_at' => now()->subDays(90),
                    ...$profile,
                ],
            );

            UserPref::query()->updateOrCreate(
                ['user_id' => $user->id],
                [
                    'user_id' => $user->id,
                    'settings' => $prefsSettings,
                ],
            );

            app(PlannerProfileSyncService::class)->prepare($user->fresh(), persistOverrides: false);
        }
    }
}
