<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AiProfileDiversitySeeder extends Seeder
{
    public function run(): void
    {
        $profiles = [
            [
                'email' => 'nadine.haddad+ai1@hayetak.local',
                'first_name' => 'Nadine',
                'last_name' => 'Haddad',
                'username' => 'nadine_haddad_ai1',
                'gender' => 'female',
                'age' => 27,
                'height_cm' => 164,
                'weight_kg' => 63.8,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Lose Weight',
                'diet_name' => 'Mediterranean',
                'allergies' => ['Milk', 'Banana'],
                'has_medical_history' => true,
                'medical_history' => 'Mild asthma with occasional seasonal flare-ups.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Hunger/low energy', 'Cravings', 'Travel/routine changes'],
                'diet_failure_other' => 'Late-night snacking during exam weeks.',
            ],
            [
                'email' => 'hassan.karam+ai2@hayetak.local',
                'first_name' => 'Hassan',
                'last_name' => 'Karam',
                'username' => 'hassan_karam_ai2',
                'gender' => 'male',
                'age' => 34,
                'height_cm' => 181,
                'weight_kg' => 94.2,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'DASH',
                'allergies' => ['Shellfish', 'Mustard'],
                'has_medical_history' => true,
                'medical_history' => 'Elevated blood pressure with a prior ankle sprain.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Social/lifestyle conflicts', 'Too restrictive'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'lina.issa+ai3@hayetak.local',
                'first_name' => 'Lina',
                'last_name' => 'Issa',
                'username' => 'lina_issa_ai3',
                'gender' => 'female',
                'age' => 31,
                'height_cm' => 170,
                'weight_kg' => 71.4,
                'dietary_goal' => 'Calorie Surplus',
                'fitness_goal' => 'Build Muscle',
                'diet_name' => 'High-Protein',
                'allergies' => ['Wheat'],
                'has_medical_history' => true,
                'medical_history' => 'Postpartum core weakness with occasional lower back tightness.',
                'activity_level' => 'Very Active',
                'workout_days_per_week' => 5,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Time/meal prep burden', 'Too expensive'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'charbel.saad+ai4@hayetak.local',
                'first_name' => 'Charbel',
                'last_name' => 'Saad',
                'username' => 'charbel_saad_ai4',
                'gender' => 'male',
                'age' => 29,
                'height_cm' => 176,
                'weight_kg' => 82.5,
                'dietary_goal' => 'Maintenance',
                'fitness_goal' => 'Recomposition',
                'diet_name' => 'Low-Carb',
                'allergies' => ['Corn', 'Celery'],
                'has_medical_history' => true,
                'medical_history' => 'Recovered shoulder impingement, avoids high overhead volume.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Lack of results', 'Confusing guidance'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'sara.mattar+ai5@hayetak.local',
                'first_name' => 'Sara',
                'last_name' => 'Mattar',
                'username' => 'sara_mattar_ai5',
                'gender' => 'female',
                'age' => 24,
                'height_cm' => 158,
                'weight_kg' => 56.1,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Maintain',
                'diet_name' => 'Vegan',
                'allergies' => ['Soy'],
                'has_medical_history' => true,
                'medical_history' => 'Iron-deficiency anemia and migraine history.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 2,
                'workout_location' => 'home',
                'tried_diet_before' => false,
                'diet_failure_reasons' => [],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'george.rahme+ai6@hayetak.local',
                'first_name' => 'George',
                'last_name' => 'Rahme',
                'username' => 'george_rahme_ai6',
                'gender' => 'male',
                'age' => 41,
                'height_cm' => 174,
                'weight_kg' => 99.8,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Lose Weight',
                'diet_name' => 'Intermittent Fasting',
                'allergies' => ['Sesame', 'Shellfish'],
                'has_medical_history' => true,
                'medical_history' => 'Type 2 diabetes and fatty liver.',
                'activity_level' => 'Sedentary',
                'workout_days_per_week' => 2,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Hunger/low energy', 'Medical reasons'],
                'diet_failure_other' => 'Night shifts disrupted fasting windows.',
            ],
            [
                'email' => 'maya.fares+ai7@hayetak.local',
                'first_name' => 'Maya',
                'last_name' => 'Fares',
                'username' => 'maya_fares_ai7',
                'gender' => 'female',
                'age' => 36,
                'height_cm' => 168,
                'weight_kg' => 78.9,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Low FODMAP',
                'allergies' => ['Garlic', 'Onion'],
                'has_medical_history' => true,
                'medical_history' => 'IBS symptoms triggered by onion and garlic.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Travel/routine changes', 'Time/meal prep burden'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'ziad.saliba+ai8@hayetak.local',
                'first_name' => 'Ziad',
                'last_name' => 'Saliba',
                'username' => 'ziad_saliba_ai8',
                'gender' => 'male',
                'age' => 22,
                'height_cm' => 183,
                'weight_kg' => 73.3,
                'dietary_goal' => 'Calorie Surplus',
                'fitness_goal' => 'Build Muscle',
                'diet_name' => 'Mediterranean',
                'allergies' => ['Peanut'],
                'has_medical_history' => true,
                'medical_history' => 'Wrist strain from boxing and mild knee pain.',
                'activity_level' => 'Very Active',
                'workout_days_per_week' => 6,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Too expensive', 'Cravings'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'rima.nasr+ai9@hayetak.local',
                'first_name' => 'Rima',
                'last_name' => 'Nasr',
                'username' => 'rima_nasr_ai9',
                'gender' => 'female',
                'age' => 47,
                'height_cm' => 161,
                'weight_kg' => 86.7,
                'dietary_goal' => 'Maintenance',
                'fitness_goal' => 'Maintain',
                'diet_name' => 'DASH',
                'allergies' => ['Fish'],
                'has_medical_history' => true,
                'medical_history' => 'Hypertension and sleep apnea.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Social/lifestyle conflicts', 'Lack of results'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'jad.chehab+ai10@hayetak.local',
                'first_name' => 'Jad',
                'last_name' => 'Chehab',
                'username' => 'jad_chehab_ai10',
                'gender' => 'male',
                'age' => 33,
                'height_cm' => 179,
                'weight_kg' => 88.0,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Recomposition',
                'diet_name' => 'Keto',
                'allergies' => ['Eggs', 'Milk'],
                'has_medical_history' => true,
                'medical_history' => 'Acid reflux and lower-back tightness.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Too restrictive', 'Hunger/low energy'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'leen.tannous+ai11@hayetak.local',
                'first_name' => 'Leen',
                'last_name' => 'Tannous',
                'username' => 'leen_tannous_ai11',
                'gender' => 'female',
                'age' => 28,
                'height_cm' => 166,
                'weight_kg' => 60.9,
                'dietary_goal' => 'Calorie Surplus',
                'fitness_goal' => 'Build Muscle',
                'diet_name' => 'Vegetarian',
                'allergies' => ['Lupin', 'Celery'],
                'has_medical_history' => true,
                'medical_history' => 'Low vitamin D and patellofemoral knee pain.',
                'activity_level' => 'Very Active',
                'workout_days_per_week' => 5,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Time/meal prep burden', 'Confusing guidance'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'fadi.ghosn+ai12@hayetak.local',
                'first_name' => 'Fadi',
                'last_name' => 'Ghosn',
                'username' => 'fadi_ghosn_ai12',
                'gender' => 'male',
                'age' => 39,
                'height_cm' => 177,
                'weight_kg' => 92.4,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Paleo',
                'allergies' => ['Wheat', 'Tomato'],
                'has_medical_history' => true,
                'medical_history' => 'Old broken ankle with occasional knee flare-ups.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Travel/routine changes', 'Cravings'],
                'diet_failure_other' => null,
            ],
            [
                'email' => 'nora.khoury+ai13@hayetak.local',
                'first_name' => 'Nora',
                'last_name' => 'Khoury',
                'username' => 'nora_khoury_ai13',
                'gender' => 'female',
                'age' => 55,
                'height_cm' => 159,
                'weight_kg' => 75.6,
                'dietary_goal' => 'Calorie Deficit',
                'fitness_goal' => 'Maintain Strength',
                'diet_name' => 'DASH',
                'allergies' => ['Tree Nuts'],
                'has_medical_history' => true,
                'medical_history' => 'Hypertension with bilateral knee osteoarthritis and occasional lower-back stiffness.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'home',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Hunger/low energy', 'Social/lifestyle conflicts'],
                'diet_failure_other' => 'Family lunches made portion control inconsistent on weekends.',
            ],
            [
                'email' => 'rami.assaad+ai14@hayetak.local',
                'first_name' => 'Rami',
                'last_name' => 'Assaad',
                'username' => 'rami_assaad_ai14',
                'gender' => 'male',
                'age' => 58,
                'height_cm' => 173,
                'weight_kg' => 83.4,
                'dietary_goal' => 'Maintenance',
                'fitness_goal' => 'Recomposition',
                'diet_name' => 'Mediterranean',
                'allergies' => ['Shrimp'],
                'has_medical_history' => true,
                'medical_history' => 'Prediabetes with a past shoulder impingement and intermittent elbow tendinopathy.',
                'activity_level' => 'Moderately Active',
                'workout_days_per_week' => 4,
                'workout_location' => 'gym',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Lack of results', 'Confusing guidance'],
                'diet_failure_other' => 'Previous plans did not account for shoulder flare-ups when training volume increased.',
            ],
            [
                'email' => 'dania.younes+ai15@hayetak.local',
                'first_name' => 'Dania',
                'last_name' => 'Younes',
                'username' => 'dania_younes_ai15',
                'gender' => 'female',
                'age' => 43,
                'height_cm' => 165,
                'weight_kg' => 68.2,
                'dietary_goal' => 'Balanced Nutrition',
                'fitness_goal' => 'Improve Endurance',
                'diet_name' => 'Gluten-Free',
                'allergies' => ['Peanut', 'Shrimp'],
                'has_medical_history' => true,
                'medical_history' => 'Celiac disease, rotator cuff irritation, and occasional plantar fasciitis after long walks.',
                'activity_level' => 'Lightly Active',
                'workout_days_per_week' => 3,
                'workout_location' => 'both',
                'tried_diet_before' => true,
                'diet_failure_reasons' => ['Travel/routine changes', 'Too expensive'],
                'diet_failure_other' => 'Restaurant meals often broke gluten-free consistency during work travel.',
            ],
        ];

        foreach ($profiles as $index => $profile) {
            $createdAt = now()->subDays(48 + ($index * 3));

            User::query()->updateOrCreate(
                ['email' => $profile['email']],
                [
                    'name' => $profile['first_name'].' '.$profile['last_name'],
                    'password' => Hash::make('password'),
                    'role' => User::ROLE_CLIENT,
                    'verified' => true,
                    'status' => 'active',
                    'created_at' => $createdAt,
                    'updated_at' => now(),
                    'email_verified_at' => now()->subDays(90),
                    ...$profile,
                ],
            );
        }
    }
}
