<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocxMealCatalogSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->docxFoods() as $food) {
            DB::table('foods')->updateOrInsert(
                ['name' => $food['name']],
                $this->normalizeFood($food)
            );
        }

        foreach ($this->existingDishMetadata() as $food) {
            DB::table('foods')
                ->where('name', $food['name'])
                ->update($this->normalizeFood($food, false));
        }
    }

    private function docxFoods(): array
    {
        return [
            [
                'name' => 'Three-Egg Cheese Avocado Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 460,
                'protein_g' => 27,
                'carbs_g' => 8,
                'fat_g' => 33,
                'fiber_g' => 5,
                'sugar_g' => 2,
                'sodium_mg' => 520,
                'cholesterol_mg' => 560,
                'tags' => ['docx', 'high-protein', 'savory'],
                'allergens' => ['eggs', 'milk'],
                'diets_allowed' => ['mediterranean', 'keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['eggs', 'cheese', 'avocado', 'sriracha', 'apple drink'],
                'meal_types' => ['breakfast'],
            ],
            [
                'name' => 'Charcoal Chicken Fattoush Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 450,
                'protein_g' => 50,
                'carbs_g' => 14,
                'fat_g' => 18,
                'fiber_g' => 4,
                'sugar_g' => 4,
                'sodium_mg' => 540,
                'cholesterol_mg' => 150,
                'tags' => ['docx', 'grilled', 'salad'],
                'allergens' => [],
                'diets_allowed' => ['mediterranean', 'dash', 'whole30', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['chicken breast', 'lettuce', 'tomato', 'cucumber', 'olive oil', 'garlic'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Banana Bread Slice',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Bakery',
                'category' => 'Snack',
                'serving_size' => 1,
                'serving_unit' => 'slice',
                'calories' => 190,
                'protein_g' => 3,
                'carbs_g' => 30,
                'fat_g' => 7,
                'fiber_g' => 2,
                'sugar_g' => 16,
                'sodium_mg' => 170,
                'cholesterol_mg' => 28,
                'tags' => ['docx', 'sweet-snack', 'bakery'],
                'allergens' => ['banana', 'eggs', 'milk', 'wheat'],
                'diets_allowed' => ['vegetarian'],
                'ingredients' => ['banana', 'flour', 'egg', 'butter', 'sugar'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Tuna Dill Pickle Bowl',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Protein Bowl',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 220,
                'protein_g' => 40,
                'carbs_g' => 3,
                'fat_g' => 5,
                'fiber_g' => 1,
                'sugar_g' => 2,
                'sodium_mg' => 760,
                'cholesterol_mg' => 55,
                'tags' => ['docx', 'high-protein', 'quick-meal'],
                'allergens' => ['fish', 'mustard'],
                'diets_allowed' => ['mediterranean', 'keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['tuna', 'dill pickles', 'mustard', 'sriracha'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Cottage Cheese Strawberry Turkey Bowl',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'High Protein',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 250,
                'protein_g' => 30,
                'carbs_g' => 14,
                'fat_g' => 8,
                'fiber_g' => 2,
                'sugar_g' => 9,
                'sodium_mg' => 520,
                'cholesterol_mg' => 55,
                'tags' => ['docx', 'high-protein', 'breakfast'],
                'allergens' => ['milk'],
                'diets_allowed' => ['high-protein', 'low-carb', 'gluten-free'],
                'ingredients' => ['cottage cheese', 'strawberries', 'smoked turkey', 'honey', 'monk fruit'],
                'meal_types' => ['breakfast'],
            ],
            [
                'name' => 'Lean Beef Rice Laban Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 700,
                'protein_g' => 55,
                'carbs_g' => 52,
                'fat_g' => 28,
                'fiber_g' => 4,
                'sugar_g' => 6,
                'sodium_mg' => 720,
                'cholesterol_mg' => 140,
                'tags' => ['docx', 'high-protein', 'beef'],
                'allergens' => ['milk'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['lean beef steak', 'olive oil', 'rice', 'laban', 'lettuce', 'tomato', 'cucumber', 'pomegranate molasses'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Labneh Lean Beef Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 240,
                'protein_g' => 30,
                'carbs_g' => 4,
                'fat_g' => 11,
                'fiber_g' => 0,
                'sugar_g' => 2,
                'sodium_mg' => 430,
                'cholesterol_mg' => 85,
                'tags' => ['docx', 'high-protein', 'low-carb'],
                'allergens' => ['milk'],
                'diets_allowed' => ['mediterranean', 'keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['labneh', 'lean beef'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Turkey Egg Avocado Toast',
                'brand' => 'Prunelle',
                'nationality' => 'Lebanese',
                'cuisine' => 'Breakfast Sandwich',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'toast',
                'calories' => 280,
                'protein_g' => 25,
                'carbs_g' => 13,
                'fat_g' => 13,
                'fiber_g' => 3,
                'sugar_g' => 2,
                'sodium_mg' => 480,
                'cholesterol_mg' => 215,
                'tags' => ['docx', 'high-protein', 'toast'],
                'allergens' => ['eggs', 'wheat'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['brown pain de mie', 'egg', 'egg white', 'smoked turkey', 'avocado', 'sriracha'],
                'meal_types' => ['breakfast'],
            ],
            [
                'name' => 'Chicken Creme Fraiche Pasta Plate',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Pasta',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 500,
                'protein_g' => 40,
                'carbs_g' => 30,
                'fat_g' => 22,
                'fiber_g' => 4,
                'sugar_g' => 4,
                'sodium_mg' => 520,
                'cholesterol_mg' => 115,
                'tags' => ['docx', 'pasta', 'high-protein'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['chicken', 'whole wheat pasta', 'creme fraiche', 'butter'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Salmon Cucumber Spring Roll Plate',
                'brand' => 'Plein Soleil',
                'nationality' => 'International',
                'cuisine' => 'Fusion',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 415,
                'protein_g' => 30,
                'carbs_g' => 14,
                'fat_g' => 24,
                'fiber_g' => 2,
                'sugar_g' => 3,
                'sodium_mg' => 540,
                'cholesterol_mg' => 70,
                'tags' => ['docx', 'salmon', 'quick-dinner'],
                'allergens' => ['fish', 'milk', 'wheat'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['salmon', 'cucumber', 'light philadelphia', 'spring rolls'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Kafta Tabbouleh Hummus Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 500,
                'protein_g' => 38,
                'carbs_g' => 25,
                'fat_g' => 28,
                'fiber_g' => 5,
                'sugar_g' => 3,
                'sodium_mg' => 650,
                'cholesterol_mg' => 90,
                'tags' => ['docx', 'lebanese', 'plate'],
                'allergens' => ['sesame', 'wheat'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['kafta', 'parsley', 'tomato', 'bulgur', 'hummus'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Rice Pop Peanut Butter Honey Snack',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Snack',
                'category' => 'Snack',
                'serving_size' => 2,
                'serving_unit' => 'rice pops',
                'calories' => 200,
                'protein_g' => 6,
                'carbs_g' => 24,
                'fat_g' => 10,
                'fiber_g' => 2,
                'sugar_g' => 10,
                'sodium_mg' => 120,
                'cholesterol_mg' => 0,
                'tags' => ['docx', 'sweet-snack'],
                'allergens' => ['peanuts'],
                'diets_allowed' => ['vegetarian', 'gluten-free'],
                'ingredients' => ['rice cakes', 'peanut butter', 'honey'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Air Fryer Salmon Potato Plate',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Mediterranean',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 390,
                'protein_g' => 33,
                'carbs_g' => 18,
                'fat_g' => 20,
                'fiber_g' => 3,
                'sugar_g' => 2,
                'sodium_mg' => 380,
                'cholesterol_mg' => 78,
                'tags' => ['docx', 'salmon', 'air-fryer'],
                'allergens' => ['fish', 'eggs'],
                'diets_allowed' => ['mediterranean', 'dash', 'high-protein', 'gluten-free'],
                'ingredients' => ['salmon', 'light mayo', 'baked potato'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Strawberry Mango Protein Yogurt Bowl',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Breakfast Bowl',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 340,
                'protein_g' => 28,
                'carbs_g' => 33,
                'fat_g' => 9,
                'fiber_g' => 3,
                'sugar_g' => 22,
                'sodium_mg' => 120,
                'cholesterol_mg' => 28,
                'tags' => ['docx', 'breakfast', 'fruit'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'high-protein', 'gluten-free'],
                'ingredients' => ['greek yogurt', 'strawberries', 'mango', 'collagen powder', 'honey', 'monk fruit'],
                'meal_types' => ['breakfast'],
            ],
            [
                'name' => 'Chicken Liver Warak Enab Salad Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 600,
                'protein_g' => 40,
                'carbs_g' => 24,
                'fat_g' => 32,
                'fiber_g' => 5,
                'sugar_g' => 4,
                'sodium_mg' => 760,
                'cholesterol_mg' => 315,
                'tags' => ['docx', 'lebanese', 'iron-rich'],
                'allergens' => ['sesame'],
                'diets_allowed' => ['mediterranean', 'high-protein', 'gluten-free'],
                'ingredients' => ['salad greens', 'green onion', 'cucumber', 'olive oil', 'lemon', 'chicken liver', 'hummus', 'pomegranate molasses', 'warak enab'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Turkey Gouda Brown Toast Sandwich',
                'brand' => 'Plein Soleil',
                'nationality' => 'Lebanese',
                'cuisine' => 'Sandwich',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'sandwich',
                'calories' => 550,
                'protein_g' => 57,
                'carbs_g' => 30,
                'fat_g' => 22,
                'fiber_g' => 4,
                'sugar_g' => 4,
                'sodium_mg' => 980,
                'cholesterol_mg' => 110,
                'tags' => ['docx', 'sandwich', 'high-protein'],
                'allergens' => ['milk', 'mustard', 'wheat', 'eggs'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['brown pain demi', 'lean beef', 'kashkaval light', 'smoked turkey', 'light mayo', 'mustard'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Protein Oatmeal Bowl',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Breakfast',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 200,
                'protein_g' => 13,
                'carbs_g' => 24,
                'fat_g' => 6,
                'fiber_g' => 4,
                'sugar_g' => 5,
                'sodium_mg' => 110,
                'cholesterol_mg' => 12,
                'tags' => ['docx', 'oatmeal', 'high-protein'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'high-protein'],
                'ingredients' => ['oats', 'protein powder'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Protein Flatbread Cheese Melt',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Flatbread',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'flatbread',
                'calories' => 460,
                'protein_g' => 35,
                'carbs_g' => 27,
                'fat_g' => 20,
                'fiber_g' => 2,
                'sugar_g' => 3,
                'sodium_mg' => 620,
                'cholesterol_mg' => 70,
                'tags' => ['docx', 'vegetarian', 'high-protein'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['vegetarian', 'high-protein'],
                'ingredients' => ['brown flour', 'greek yogurt', 'parmesan', 'kashkaval'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Protein Pudding Cup',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Snack',
                'category' => 'Snack',
                'serving_size' => 1,
                'serving_unit' => 'cup',
                'calories' => 150,
                'protein_g' => 20,
                'carbs_g' => 12,
                'fat_g' => 3,
                'fiber_g' => 0,
                'sugar_g' => 9,
                'sodium_mg' => 130,
                'cholesterol_mg' => 10,
                'tags' => ['docx', 'high-protein', 'dessert'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'high-protein', 'gluten-free'],
                'ingredients' => ['milk protein pudding'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Boiled eggs and cherry tomatoes',
                'brand' => null,
                'nationality' => 'Mediterranean',
                'cuisine' => 'Snack Plate',
                'category' => 'Snack',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 165,
                'protein_g' => 13,
                'carbs_g' => 4,
                'fat_g' => 11,
                'fiber_g' => 1,
                'sugar_g' => 2,
                'sodium_mg' => 180,
                'cholesterol_mg' => 370,
                'tags' => ['docx', 'high-protein', 'snack', 'savory'],
                'allergens' => ['eggs'],
                'diets_allowed' => ['mediterranean', 'low-carb', 'high-protein', 'gluten-free', 'whole30', 'paleo'],
                'ingredients' => ['boiled eggs', 'cherry tomatoes', 'olive oil', 'salt', 'black pepper'],
                'meal_types' => ['snack', 'breakfast'],
            ],
            [
                'name' => 'Chicken Brown Pasta Cream Plate',
                'brand' => 'President',
                'nationality' => 'International',
                'cuisine' => 'Pasta',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 540,
                'protein_g' => 47,
                'carbs_g' => 39,
                'fat_g' => 20,
                'fiber_g' => 4,
                'sugar_g' => 5,
                'sodium_mg' => 540,
                'cholesterol_mg' => 115,
                'tags' => ['docx', 'pasta', 'high-protein'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['brown pasta', 'marinated chicken', 'butter', 'olive oil', 'light cream fraiche', 'mozzarella', 'red onion', 'garlic'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Chocolate Protein Shake',
                'brand' => 'Basic Supplements',
                'nationality' => 'International',
                'cuisine' => 'Shake',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'shake',
                'calories' => 220,
                'protein_g' => 32,
                'carbs_g' => 10,
                'fat_g' => 5,
                'fiber_g' => 1,
                'sugar_g' => 8,
                'sodium_mg' => 180,
                'cholesterol_mg' => 18,
                'tags' => ['docx', 'shake', 'high-protein'],
                'allergens' => ['milk'],
                'diets_allowed' => ['high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['chocolate protein powder', 'lactose free milk'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Chicken Mozzarella Pasta Bake',
                'brand' => 'President',
                'nationality' => 'International',
                'cuisine' => 'Pasta',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 560,
                'protein_g' => 50,
                'carbs_g' => 44,
                'fat_g' => 18,
                'fiber_g' => 4,
                'sugar_g' => 5,
                'sodium_mg' => 600,
                'cholesterol_mg' => 120,
                'tags' => ['docx', 'pasta', 'high-protein'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['grilled chicken', 'brown pasta', 'light cooking cream', 'onion', 'garlic', 'mozzarella'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Chicken Caesar Salad Bowl',
                'brand' => null,
                'nationality' => 'International',
                'cuisine' => 'Salad',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 650,
                'protein_g' => 58,
                'carbs_g' => 18,
                'fat_g' => 36,
                'fiber_g' => 4,
                'sugar_g' => 4,
                'sodium_mg' => 840,
                'cholesterol_mg' => 155,
                'tags' => ['docx', 'salad', 'high-protein'],
                'allergens' => ['eggs', 'fish', 'milk', 'wheat'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['romaine lettuce', 'chicken', 'caesar dressing', 'parmesan', 'croutons'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Chicken Thigh Air Fryer Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 365,
                'protein_g' => 41,
                'carbs_g' => 10,
                'fat_g' => 18,
                'fiber_g' => 2,
                'sugar_g' => 2,
                'sodium_mg' => 340,
                'cholesterol_mg' => 125,
                'tags' => ['docx', 'air-fryer', 'high-protein'],
                'allergens' => ['eggs'],
                'diets_allowed' => ['low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['tabbouleh without bulgur', 'chicken thighs', 'air fryer fries', 'thousand island sauce'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Chocolate Protein Oats Bowl',
                'brand' => 'Basic Supplements',
                'nationality' => 'International',
                'cuisine' => 'Dessert Bowl',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 400,
                'protein_g' => 33,
                'carbs_g' => 35,
                'fat_g' => 13,
                'fiber_g' => 4,
                'sugar_g' => 16,
                'sodium_mg' => 190,
                'cholesterol_mg' => 16,
                'tags' => ['docx', 'high-protein', 'dessert'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['oats', 'lactose free milk', 'chocolate protein powder', 'cocoa powder', 'kinder maxi', 'honey'],
                'meal_types' => ['breakfast', 'snack', 'dinner'],
            ],
            [
                'name' => 'Kafta Hummus Pepper Plate',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Mediterranean',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 380,
                'protein_g' => 35,
                'carbs_g' => 13,
                'fat_g' => 22,
                'fiber_g' => 4,
                'sugar_g' => 4,
                'sodium_mg' => 500,
                'cholesterol_mg' => 88,
                'tags' => ['docx', 'lebanese', 'low-carb'],
                'allergens' => ['sesame'],
                'diets_allowed' => ['mediterranean', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['kafta', 'hummus', 'bell pepper'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Smoked Turkey Roll-Ups',
                'brand' => 'La Piara',
                'nationality' => 'International',
                'cuisine' => 'Snack',
                'category' => 'Snack',
                'serving_size' => 3,
                'serving_unit' => 'slices',
                'calories' => 60,
                'protein_g' => 10,
                'carbs_g' => 1,
                'fat_g' => 2,
                'fiber_g' => 0,
                'sugar_g' => 0,
                'sodium_mg' => 420,
                'cholesterol_mg' => 18,
                'tags' => ['docx', 'high-protein', 'snack'],
                'allergens' => [],
                'diets_allowed' => ['keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['smoked turkey'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Edamame Snack Bowl',
                'brand' => null,
                'nationality' => 'Japanese',
                'cuisine' => 'Snack',
                'category' => 'Snack',
                'serving_size' => 1,
                'serving_unit' => 'bowl',
                'calories' => 120,
                'protein_g' => 11,
                'carbs_g' => 10,
                'fat_g' => 4,
                'fiber_g' => 5,
                'sugar_g' => 2,
                'sodium_mg' => 15,
                'cholesterol_mg' => 0,
                'tags' => ['docx', 'vegan', 'snack'],
                'allergens' => ['soy'],
                'diets_allowed' => ['vegan', 'vegetarian', 'gluten-free', 'high-protein'],
                'ingredients' => ['edamame'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Salmon Sushi Combo',
                'brand' => 'Kanu Sushi',
                'nationality' => 'Japanese',
                'cuisine' => 'Japanese',
                'category' => 'Lunch',
                'serving_size' => 1,
                'serving_unit' => 'combo',
                'calories' => 700,
                'protein_g' => 55,
                'carbs_g' => 52,
                'fat_g' => 28,
                'fiber_g' => 3,
                'sugar_g' => 6,
                'sodium_mg' => 980,
                'cholesterol_mg' => 95,
                'tags' => ['docx', 'restaurant', 'sushi'],
                'allergens' => ['fish', 'sesame', 'soy', 'wheat'],
                'diets_allowed' => ['mediterranean', 'high-protein'],
                'ingredients' => ['salmon roll', 'salmon sashimi', 'sushi rice', 'soy sauce'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Vodka Pasta Chicken Plate',
                'brand' => null,
                'nationality' => 'Italian',
                'cuisine' => 'Pasta',
                'category' => 'Dinner',
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'calories' => 650,
                'protein_g' => 36,
                'carbs_g' => 58,
                'fat_g' => 27,
                'fiber_g' => 4,
                'sugar_g' => 7,
                'sodium_mg' => 620,
                'cholesterol_mg' => 105,
                'tags' => ['docx', 'restaurant', 'pasta'],
                'allergens' => ['milk', 'wheat', 'tomato'],
                'diets_allowed' => ['high-protein'],
                'ingredients' => ['vodka pasta', 'chicken', 'tomato sauce', 'cream', 'pasta'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Brown Yogurt Flatbread Kashkaval',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Flatbread',
                'category' => 'Breakfast',
                'serving_size' => 1,
                'serving_unit' => 'flatbread',
                'calories' => 265,
                'protein_g' => 17,
                'carbs_g' => 18,
                'fat_g' => 13,
                'fiber_g' => 2,
                'sugar_g' => 3,
                'sodium_mg' => 420,
                'cholesterol_mg' => 42,
                'tags' => ['docx', 'vegetarian', 'breakfast'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['vegetarian', 'high-protein'],
                'ingredients' => ['brown flour', 'greek yogurt', 'kashkaval light'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Kinder Maxi Bar',
                'brand' => 'Kinder',
                'nationality' => 'European',
                'cuisine' => 'Snack',
                'category' => 'Snack',
                'serving_size' => 1,
                'serving_unit' => 'bar',
                'calories' => 118,
                'protein_g' => 2,
                'carbs_g' => 13,
                'fat_g' => 6,
                'fiber_g' => 0,
                'sugar_g' => 11,
                'sodium_mg' => 40,
                'cholesterol_mg' => 8,
                'tags' => ['docx', 'sweet-snack', 'treat'],
                'allergens' => ['milk', 'soy', 'wheat'],
                'diets_allowed' => ['vegetarian'],
                'ingredients' => ['milk chocolate', 'wafer', 'milk filling'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Low-Fat Labneh Dip',
                'brand' => null,
                'nationality' => 'Lebanese',
                'cuisine' => 'Dip',
                'category' => 'Snack',
                'serving_size' => 2,
                'serving_unit' => 'tbsp',
                'calories' => 70,
                'protein_g' => 3,
                'carbs_g' => 2,
                'fat_g' => 5,
                'fiber_g' => 0,
                'sugar_g' => 1,
                'sodium_mg' => 150,
                'cholesterol_mg' => 10,
                'tags' => ['docx', 'dip', 'low-carb'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'keto', 'low-carb', 'gluten-free'],
                'ingredients' => ['labneh'],
                'meal_types' => ['snack'],
            ],
        ];
    }

    private function existingDishMetadata(): array
    {
        return [
            [
                'name' => 'Chickpea Tomato Breakfast Bowl',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'vegan', 'breakfast'],
                'allergens' => [],
                'diets_allowed' => ['vegan', 'vegetarian', 'mediterranean', 'dash', 'gluten-free'],
                'ingredients' => ['chickpeas', 'tomato', 'spinach', 'olive oil', 'herbs'],
                'meal_types' => ['breakfast', 'lunch'],
            ],
            [
                'name' => 'Herb Chicken Quinoa Plate',
                'category' => 'Lunch',
                'tags' => ['seeded', 'high-protein'],
                'allergens' => [],
                'diets_allowed' => ['mediterranean', 'dash', 'high-protein', 'gluten-free'],
                'ingredients' => ['chicken', 'quinoa', 'zucchini', 'herbs', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Baked Salmon Potato Tray',
                'category' => 'Dinner',
                'tags' => ['seeded', 'salmon'],
                'allergens' => ['fish'],
                'diets_allowed' => ['mediterranean', 'dash', 'high-protein', 'gluten-free'],
                'ingredients' => ['salmon', 'potato', 'olive oil', 'herbs'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Avocado Egg Plate',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'breakfast', 'low-carb'],
                'allergens' => ['eggs', 'avocado'],
                'diets_allowed' => ['keto', 'low-carb', 'whole30', 'paleo', 'high-protein', 'gluten-free'],
                'ingredients' => ['eggs', 'avocado', 'olive oil'],
                'meal_types' => ['breakfast'],
            ],
            [
                'name' => 'Beef Zucchini Skillet',
                'category' => 'Lunch',
                'tags' => ['seeded', 'low-carb', 'beef'],
                'allergens' => [],
                'diets_allowed' => ['keto', 'low-carb', 'whole30', 'paleo', 'high-protein', 'gluten-free'],
                'ingredients' => ['beef', 'zucchini', 'olive oil', 'herbs'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Salmon Broccoli Butter Plate',
                'category' => 'Dinner',
                'tags' => ['seeded', 'salmon', 'low-carb'],
                'allergens' => ['fish', 'milk'],
                'diets_allowed' => ['keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['salmon', 'broccoli', 'butter'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Turkey Sweet Potato Hash',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'hash', 'high-protein'],
                'allergens' => [],
                'diets_allowed' => ['whole30', 'paleo', 'high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['turkey', 'sweet potato', 'peppers', 'olive oil'],
                'meal_types' => ['breakfast', 'lunch', 'dinner'],
            ],
            [
                'name' => 'Lemon Chicken Root Veg Plate',
                'category' => 'Lunch',
                'tags' => ['seeded', 'lemon', 'high-protein'],
                'allergens' => [],
                'diets_allowed' => ['whole30', 'paleo', 'mediterranean', 'dash', 'high-protein', 'gluten-free'],
                'ingredients' => ['chicken', 'carrot', 'parsnip', 'potato', 'lemon', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Beef Vegetable Stew Bowl',
                'category' => 'Dinner',
                'tags' => ['seeded', 'stew'],
                'allergens' => [],
                'diets_allowed' => ['mediterranean', 'dash', 'high-protein', 'gluten-free'],
                'ingredients' => ['beef', 'carrot', 'celery', 'potato', 'tomato', 'stock'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Chia Berry Breakfast Jar',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'breakfast', 'fiber'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'mediterranean', 'dash', 'gluten-free'],
                'ingredients' => ['chia seeds', 'berries', 'greek yogurt', 'honey'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Lentil Quinoa Power Bowl',
                'category' => 'Lunch',
                'tags' => ['seeded', 'vegan', 'bowl'],
                'allergens' => [],
                'diets_allowed' => ['vegan', 'vegetarian', 'mediterranean', 'dash', 'gluten-free'],
                'ingredients' => ['lentils', 'quinoa', 'cucumber', 'tomato', 'parsley', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Tofu Vegetable Stir Fry',
                'category' => 'Dinner',
                'tags' => ['seeded', 'vegan', 'stir-fry'],
                'allergens' => ['soy'],
                'diets_allowed' => ['vegan', 'vegetarian', 'dash', 'gluten-free'],
                'ingredients' => ['tofu', 'broccoli', 'bell pepper', 'carrot', 'tamari'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Greek Yogurt Fruit Bowl',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'yogurt', 'high-protein'],
                'allergens' => ['milk', 'banana'],
                'diets_allowed' => ['vegetarian', 'high-protein', 'dash', 'gluten-free'],
                'ingredients' => ['greek yogurt', 'berries', 'banana', 'honey'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Protein Yogurt Cup',
                'category' => 'Snack',
                'tags' => ['seeded', 'high-protein', 'snack'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'high-protein', 'gluten-free'],
                'ingredients' => ['greek yogurt', 'protein powder', 'berries'],
                'meal_types' => ['snack'],
            ],
            [
                'name' => 'Halloumi Bulgur Salad',
                'category' => 'Lunch',
                'tags' => ['seeded', 'vegetarian', 'salad'],
                'allergens' => ['milk', 'wheat'],
                'diets_allowed' => ['vegetarian', 'mediterranean'],
                'ingredients' => ['halloumi', 'bulgur', 'tomato', 'cucumber', 'parsley'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Lentil Stuffed Pepper Plate',
                'category' => 'Dinner',
                'tags' => ['seeded', 'vegan', 'stuffed-pepper'],
                'allergens' => [],
                'diets_allowed' => ['vegan', 'vegetarian', 'dash', 'gluten-free'],
                'ingredients' => ['lentils', 'bell pepper', 'rice', 'tomato', 'parsley'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Rice Flakes Berry Bowl',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'gluten-free', 'breakfast'],
                'allergens' => ['milk'],
                'diets_allowed' => ['vegetarian', 'dash', 'gluten-free', 'low fodmap'],
                'ingredients' => ['rice flakes', 'berries', 'milk'],
                'meal_types' => ['breakfast', 'snack'],
            ],
            [
                'name' => 'Chicken Rice Spinach Plate',
                'category' => 'Lunch',
                'tags' => ['seeded', 'high-protein', 'gluten-free'],
                'allergens' => [],
                'diets_allowed' => ['mediterranean', 'dash', 'high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['chicken', 'rice', 'spinach', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Herb Salmon Carrot Plate',
                'category' => 'Dinner',
                'tags' => ['seeded', 'salmon', 'gluten-free'],
                'allergens' => ['fish'],
                'diets_allowed' => ['whole30', 'paleo', 'mediterranean', 'dash', 'high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['salmon', 'carrot', 'herbs', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Sweet Potato Turkey Hash',
                'category' => 'Breakfast',
                'tags' => ['seeded', 'hash', 'gluten-free'],
                'allergens' => [],
                'diets_allowed' => ['whole30', 'paleo', 'high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['turkey', 'sweet potato', 'pepper', 'olive oil'],
                'meal_types' => ['breakfast', 'lunch', 'dinner'],
            ],
            [
                'name' => 'Lemon Chicken Veg Plate',
                'category' => 'Lunch',
                'tags' => ['seeded', 'chicken', 'vegetables'],
                'allergens' => [],
                'diets_allowed' => ['whole30', 'paleo', 'mediterranean', 'dash', 'high-protein', 'gluten-free', 'low fodmap'],
                'ingredients' => ['chicken', 'zucchini', 'carrot', 'green beans', 'lemon', 'olive oil'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Beef Meatballs Zucchini Plate',
                'category' => 'Dinner',
                'tags' => ['seeded', 'beef', 'low-carb'],
                'allergens' => ['eggs'],
                'diets_allowed' => ['keto', 'low-carb', 'whole30', 'paleo', 'high-protein', 'gluten-free'],
                'ingredients' => ['beef meatballs', 'zucchini', 'olive oil', 'herbs'],
                'meal_types' => ['lunch', 'dinner'],
            ],
            [
                'name' => 'Turkey Roll Ups',
                'category' => 'Snack',
                'tags' => ['seeded', 'high-protein', 'snack'],
                'allergens' => [],
                'diets_allowed' => ['keto', 'low-carb', 'high-protein', 'gluten-free'],
                'ingredients' => ['smoked turkey'],
                'meal_types' => ['snack'],
            ],
        ];
    }

    private function normalizeFood(array $food, bool $withTimestamps = true): array
    {
        $normalized = $food;

        foreach (['tags', 'allergens', 'diets_allowed', 'ingredients', 'meal_types'] as $key) {
            if (! array_key_exists($key, $normalized)) {
                continue;
            }

            $normalized[$key] = array_values(array_unique(array_map(
                static fn ($value) => mb_strtolower(trim((string) $value)),
                array_filter((array) $normalized[$key], static fn ($value) => $value !== null && trim((string) $value) !== '')
            )));
        }

        foreach (['tags', 'allergens', 'diets_allowed', 'ingredients'] as $jsonKey) {
            if (array_key_exists($jsonKey, $normalized)) {
                $normalized[$jsonKey] = json_encode($normalized[$jsonKey], JSON_THROW_ON_ERROR);
            }
        }

        if (array_key_exists('meal_types', $normalized)) {
            $normalized['meal_types'] = '{'.implode(',', $normalized['meal_types']).'}';
        }

        if ($withTimestamps) {
            $normalized['created_at'] ??= now();
        }

        $normalized['updated_at'] = now();

        return $normalized;
    }
}
